import { useEffect,useState } from 'react';
import { Link } from 'react-router-dom';
import * as Icons from 'lucide-react';
import { api } from '../services/api';
import { ProductCard,PromoCard,Skeleton } from '../components/Cards';
const benefits=[['BadgeDollarSign','Harga Jelas','Lihat harga dan tier langsung dari katalog'],['LayoutGrid','Kategori Rapi','Menu lebih cepat ditemukan'],['Search','Pencarian Cepat','Cari produk tanpa perlu login'],['RefreshCcw','Stok Terupdate','Informasi katalog lebih mudah dipantau']];
const needs=[['Untuk Warung','Lihat kebutuhan warung seperti sembako, minuman dan stok harian.','Store'],['Untuk Cafe','Jelajahi kopi, susu, gula, tissue dan kebutuhan cafe.','Coffee'],['Untuk Restoran','Lihat bahan dapur dan kebutuhan operasional restoran.','UtensilsCrossed'],['Untuk Reseller','Jelajahi produk dan tier harga grosir untuk referensi stok.','ShoppingBag']];
export default function Home(){const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[promos,setPromos]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(false);useEffect(()=>{Promise.all([api.products(),api.categories(),api.promos()]).then(([p,c,pr])=>{setProducts(p);setCategories(c);setPromos(pr)}).catch(()=>setError(true)).finally(()=>setLoading(false))},[]);return <div className="page">
 <section className="hero"><div className="heroCopy"><span className="eyebrow">WHOLESALE CATALOG · INDONESIA</span><h1>Lihat Menu Grosir<br/><em>Lebih Mudah.</em></h1><p>Buka katalog kebutuhan grosir untuk warung, restoran, cafe dan bisnis. Langsung lihat produk, kategori, harga dan promo tanpa login.</p><div><Link className="primaryBtn" to="/menu">Lihat Menu <Icons.ArrowUpRight size={18}/></Link><Link className="secondaryBtn" to="/promo">Lihat Promo</Link></div><small><Icons.ShieldCheck size={15}/> Harga transparan · stok terupdate · menu mudah dicari</small></div><div className="heroArt"><div className="warehouse"><span>GROSIRHUB</span><div className="shelves">{[1,2,3,4,5,6].map(i=><i key={i}></i>)}</div></div><div className="floatingStat"><b>10+</b><span>tier harga tersedia</span></div><div className="floatingBox">📦</div></div></section>
 <section><div className="sectionTitle"><div><span>Akses cepat</span><h2>Kategori kebutuhan usaha</h2></div><Link to="/kategori">Lihat semua <Icons.ArrowRight size={16}/></Link></div><div className="categoryGrid">{categories.slice(0,8).map(c=>{const Icon=Icons[c.icon]||Icons.Package;return <Link to={`/menu?category=${c.id}`} className="categoryCard" key={c.id}><span><Icon/></span><b>{c.name}</b><small>{c.description}</small></Link>})}</div></section>
 <section className="benefitWrap"><div className="sectionMini"><h3>Kenapa lihat katalog di GrosirHub?</h3></div><div className="benefits">{benefits.map(([icon,title,desc])=>{const Icon=Icons[icon];return <div key={title}><Icon/><span><b>{title}</b><small>{desc}</small></span></div>})}</div></section>
 <section><div className="sectionTitle"><div><span>Deal mingguan</span><h2>Promo Grosir Minggu Ini</h2></div><Link to="/promo">Semua promo <Icons.ArrowRight size={16}/></Link></div><div className="promoGrid">{promos.slice(0,3).map(p=><PromoCard key={p.id} promo={p}/>)}</div></section>
 <section><div className="sectionTitle"><div><span>Menu pilihan</span><h2>Produk Grosir Pilihan</h2></div><Link to="/menu">Lihat semua <Icons.ArrowRight size={16}/></Link></div>{error?<div className="errorState"><Icons.CloudOff/><h3>Katalog belum dapat dimuat</h3><p>Coba refresh halaman atau periksa koneksi API.</p></div>:<div className="productGrid">{loading?[1,2,3,4].map(i=><Skeleton key={i}/>):products.slice(0,8).map(p=><ProductCard key={p.id} p={p}/>)}</div>}</section>
 <section><div className="sectionTitle"><div><span>Jelajahi lebih relevan</span><h2>Berdasarkan kebutuhan usaha</h2></div></div><div className="needsGrid">{needs.map(([title,desc,icon])=>{const Icon=Icons[icon];return <Link to="/menu" key={title}><Icon/><h3>{title}</h3><p>{desc}</p><span>Lihat Menu <Icons.ArrowUpRight size={15}/></span></Link>})}</div></section>
 </div>}
