import { useEffect,useMemo,useState } from 'react';
import { Link,useSearchParams } from 'react-router-dom';
import { Search,SlidersHorizontal,ArrowUpDown,PackageSearch,ArrowRight } from 'lucide-react';
import { api } from '../services/api';import { ProductCard,Skeleton } from '../components/Cards';
import { categoryImage } from '../brandAssets';

export default function Shop({categoryMode=false}){
 const [sp]=useSearchParams();const [products,setProducts]=useState([]),[categories,setCategories]=useState([]),[loading,setLoading]=useState(true);const [search,setSearch]=useState(sp.get('q')||'');const [category,setCategory]=useState(sp.get('category')||'all');const [sort,setSort]=useState('popular');
 useEffect(()=>{Promise.all([api.products(),api.categories()]).then(([p,c])=>{setProducts(p);setCategories(c)}).finally(()=>setLoading(false))},[]);
 const filtered=useMemo(()=>{let p=products.filter(x=>(category==='all'||x.category===category)&&x.name.toLowerCase().includes(search.toLowerCase()));return [...p].sort((a,b)=>sort==='price-asc'?a.wholesalePrice-b.wholesalePrice:sort==='price-desc'?b.wholesalePrice-a.wholesalePrice:sort==='newest'?b.createdAt.localeCompare(a.createdAt):Number(b.featured)-Number(a.featured))},[products,category,search,sort]);
 if(categoryMode)return <div className="page categoryPage"><div className="shopHero categoryHero"><span>KATEGORI JJ TWINS MART</span><h1>Pilih kategori, lalu lihat produknya.</h1><p>Halaman kategori sekarang dibuat khusus sebagai pintu masuk visual. Pilih satu kategori untuk membuka menu yang sudah otomatis terfilter.</p></div><div className="categoryShowcaseGrid">{loading?[1,2,3,4,5,6].map(i=><div className="categoryShowcaseCard skeletonCategory" key={i}/>):categories.map(c=>{const total=products.filter(p=>p.category===c.id).length;return <Link className="categoryShowcaseCard" to={`/menu?category=${c.id}`} key={c.id}><img src={categoryImage(c)} alt={c.name}/><div className="categoryShowcaseOverlay"><span>{total} produk</span><h2>{c.name}</h2><p>{c.description}</p><b>Jelajahi kategori <ArrowRight size={16}/></b></div></Link>})}</div></div>;
 return <div className="page shopPage"><div className="shopHero menuHero"><span>MENU JJ TWINS MART</span><h1>Lihat semua menu & harga dalam satu halaman.</h1><p>Cari produk, filter kategori, urutkan harga, lalu buka detail. Tidak ada login, keranjang, atau checkout.</p></div><div className="mobileFilters"><button><SlidersHorizontal/> Filter</button><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Pilihan Utama</option><option value="price-asc">Harga Termurah</option><option value="price-desc">Harga Tertinggi</option><option value="newest">Terbaru</option></select></div><div className="shopLayout"><aside><div className="filterHead"><SlidersHorizontal/> Filter Menu</div><label>Pencarian<div className="filterSearch"><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari produk..."/></div></label><label>Kategori<select value={category} onChange={e=>setCategory(e.target.value)}><option value="all">Semua kategori</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Urutkan<select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Pilihan Utama</option><option value="price-asc">Harga Termurah</option><option value="price-desc">Harga Tertinggi</option><option value="newest">Terbaru</option></select></label><div className="filterNote"><PackageSearch/><b>Harga bertingkat tersedia</b><p>Buka detail produk untuk melihat tier harga dan informasi kemasan.</p></div></aside><div className="shopContent"><div className="resultBar"><b>{loading?'Memuat...':`${filtered.length} produk`}</b><span><ArrowUpDown/> Harga katalog ditampilkan per item</span></div><div className="productGrid">{loading?[1,2,3,4,5,6,7,8].map(i=><Skeleton key={i}/>):filtered.map(p=><ProductCard key={p.id} p={p}/>)}</div>{!loading&&filtered.length===0&&<div className="errorState"><PackageSearch/><h3>Produk belum ditemukan</h3><p>Coba kata kunci atau kategori lain.</p></div>}</div></div></div>
}
